title:              INES hackathons
email:              annefou@geo.uio.no
description:        Hackathons for norESM e-infrastructure
author:             Michael Schulz and Anne Fouilloux
baseurl:            "/INES-hackathons"
url:                "https://noresmhub.github.io"

# Social Profiles
twitter_username:   AnneFouilloux
github_username:    annefou

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
